### ISSUE TITLE
Deepworld Login / New Player

### ISSUE THREAD

**Issue by x-BeIoved** [kuroppoi/brainwine#11]
Good afternoon,

I just wondered how we would be able to fix the "Couldn't connect to the search service. Please try again in a bit." I'm currently doing this off of steam on a Windows 10 Computer. I would like to revisit the memories and things that happened with Deepworld.

Is there a fix to this?

**Comment by kuroppoi** [comment]
Could be multiple things.

Are you sure you patched your client correctly?
Are you sure the server is on?

**Comment by kuroppoi** [comment]
Inactive, feel free to re-open if you require more assistance.
