### ISSUE TITLE
Large amount of entities causes severe network latency on v2 clients

### ISSUE THREAD

**Issue by kuroppoi** [kuroppoi/brainwine#13]
This is probably because a separate packet is sent for each movement update. Should really look into improving network efficiency by implementing collection messages.

**Comment by kuroppoi** [comment]
After testing it out, sending everything in one packet significantly boosts performance, but it can still handle nowhere near what v3 clients can. (although this might be because of difference in hardware)
Definitely worth looking at sometime though, as it may improve server performance as well.

**Comment by StevenCrazyFire** [comment]
sorry but how do you fix the invalid token relog to retry error?

**Comment by kuroppoi** [comment]
Solved with commit 0d36d7cb65b92ea31d5a2676469510603d4e9d0d
