### ISSUE TITLE
Automatic max stats

### ISSUE THREAD

**Issue by StevenCrazyFire** [kuroppoi/brainwine#16]
Hi again! 
There's an issue here but Idk why when I start a new account, my character seems to have all of it's skills maxed out and HP 10 
My friend seems to have everything fine while starting at low level and 0 skills
How can fix it

**Comment by StevenCrazyFire** [comment]
Also apparently my friend doesn't have premium so he can't upgrade to past 3

**Comment by kuroppoi** [comment]
You have to update your server to the latest version. Or join your friend in theirs.

**Comment by FreddyFazbear16** [comment]
yah me too

**Comment by FreddyFazbear16** [comment]
also how do you join or make your friend join your server? do you just paste your IP from the API file to them and have them paste that in their file and connect?

**Comment by kuroppoi** [comment]
> also how do you join or make your friend join your server? do you just paste your IP from the API file to them and have them paste that in their file and connect?

The server host has to: 
- Open TCP ports 5001, 5002 and 5003. (portforwarding, you're on your own there)
- Set the value of `game_server_ip` in `api.json` to the host's public IP address.

People who want to connect have to:
- Use a modified `host.reg` (found in the Windows patching kit) where all instances of `127.0.0.1` are replaced with the host's public IP address.

You can use a simple text editor to modify the `host.reg` file.

For example:
For the server host, if your public IP is `127.67.3.65`, then your `api.json` should look something like this:
```json
{
  "game_server_ip": "127.67.3.65",
  "game_server_port": 5002,
  "gateway_port": 5001,
  "portal_port": 5003,
  "news": [
    {
      "title": "Default News",
      "content": "This news entry was automatically generated.\nEdit 'api.json' to make your own!",
      "published_at": "A long time ago..."
    }
  ]
}
```

Then, you can edit `host.reg` to look like this:
```reg
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\Bytebin LLC\Deepworld]
"gateway"="127.67.3.65:5001"
"api"="127.67.3.65:5003"
```
Make sure that you are using your *public* IP and not your machine's private IP.
Also do not to remove the port suffixes. (`:5001` and `:5003`)
You can then send your modified `host.reg` file to your friends who want to join your server.
All they will have to do to join is run that file. They do not need to run a server themselves in order to play on another's.

Good luck and I hope this helps!

**Comment by StevenCrazyFire** [comment]
Well, we both managed to get everything done, I edited my API file with my public IP but I can't edit host.reg. how can I edit a reg file?
And then when I edit host.reg, do I just drop the file on discord have them download it and run host and open deepworld while my brainwine is running?

**Comment by kuroppoi** [comment]
> Well, we both managed to get everything done, I edited my API file with my public IP but I can't edit host.reg. how can I edit a reg file? And then when I edit host.reg, do I just drop the file on discord have them download it and run host and open deepworld while my brainwine is running?
> 
> Also: do we have to keep remaking characters from scratch each time we update/play singleplayer? Like if my friend connects to my server via host.reg, he can't play on his own anymore?

You can edit `.reg` files by right clicking and then selecting Edit. For some reason it will treat it as if you're running it, so just click Run if you are prompted to.

Yes, all they will have to do is run the file and open the game.

You do not have to make new characters each time you update. Just make sure not to delete your brainwine folder, as that is where all player and world data is stored. Dragging & dropping the updated version to the same location and then replacing all files when prompted is the preferable way to update.

People can switch back to their own local server any time by simply running the unedited `host.reg` file included in the Windows patching kit. Naturally, they won't be able to play on their own server with an account made on another server (and vice versa) **so make sure to register your accounts so you don't lose them!**

**Comment by StevenCrazyFire** [comment]
Ok so everything worked! However
I edited my host.reg file and ran my server eith brainwine and sent that host.reg to my friend who ran the file but still couldn't connect

**Comment by kuroppoi** [comment]
> Ok so everything worked! However I edited my host.reg file and ran my server eith brainwine and sent that host.reg to my friend who ran the file but still couldn't connect

You might have to portforward, then.

**Comment by StevenCrazyFire** [comment]
I could connect, but they couldn't

**Comment by kuroppoi** [comment]
> I could connect, but they couldn't

That's interesting.. Where'd you get your public IP from?

**Comment by StevenCrazyFire** [comment]
I tried to use the IP found by googling my IP, of course that didn't work so instead I ran ipconfig and grabbed my ipv4 address and tried that. Worked well for me, not him.

**Comment by kuroppoi** [comment]
> I tried to use the IP found by googling my IP, of course that didn't work so instead I ran ipconfig and grabbed my ipv4 address and tried that. Worked well for me, not him.

ipconfig shows your machine’s private IP, not your public IP. If your public IP didn’t work, double check your `api.json` and `host.reg` and if everything checks out then you probably haven’t portforwarded, so look into that.

**Comment by StevenCrazyFire** [comment]
So what's the server configuration update? 
Can It let you host a server or something much easier? Because port forwarding isn't exactly something I can do

**Comment by kuroppoi** [comment]
> So what's the server configuration update?
> Can It let you host a server or something much easier? Because port forwarding isn't exactly something I can do

I unfortunately cannot make it easier for you, as port forwarding is a requirement for hosting pretty much any public game server. Alternatives could be hiring dedicated server hardware, or asking a friend who is able to port forward to host it for you. You can also use software like Hamachi, which would allow your friends to join you through your private IP and without needing to port forward.

**Comment by StevenCrazyFire** [comment]
hamachi works

**Comment by kuroppoi** [comment]
Glad to hear it, I'll close this issue then.
