### ISSUE TITLE
Bug where the world flips and blocks disappear?

### ISSUE THREAD

**Issue by Frydi** [kuroppoi/brainwine#17]
I keep running into a bug as soon as I run out of my spawn area where the world will flip and tiles will start disappearing completely and I fall into the void, can anyone help? I've tried restarting the game and the server itself, but nothing's worked so far.

**Comment by kuroppoi** [comment]
Weird, I have never encountered such a thing before. Would it be possible to record some video footage of it when it occurs and send it here?

**Comment by Frydi** [comment]
I could try to record something, yes, let me see what I can do.

**Comment by Frydi** [comment]
![image](https://user-images.githubusercontent.com/111468357/185269240-e5038b23-a596-4428-94a5-eab7496aeccc.png)

There are a few other bugs that occur, like the world I'm in being the only one I can travel to and some textures being missing. Couldn't seem to record a video, but this is what happens.

**Comment by kuroppoi** [comment]
I have actually experienced this before when I attempted to inject a DLL during runtime. No idea what exactly triggered it, though. I suppose one thing you could try is verifying Deepworld's game file integrity through Steam and see if perhaps any files are corrupted/modified and are causing issues. The logs you mentioned are harmless warnings and are unrelated, so don't worry about those.

As for your other issue, if your current world is the only one available then that is simply the only one that exists.

**Comment by Frydi** [comment]
Alright, thanks, I'll try that. Thanks for your time!

**Comment by kuroppoi** [comment]
No problem, let me know if your issue persists or if you have any others,

**Comment by Frydi** [comment]
I ran the verification check and it found that 2 files were missing/corrupted, but it seems to be working now. Thanks again.

**Comment by kuroppoi** [comment]
I should mention that one of those 2 repaired files is the patched `Assembly-CSharp.dll` which has now been undone by Steam.
Not an issue if you're only playing locally, but should you ever want to play on a non-local server then make sure to patch the client again.
