### ISSUE TITLE
Steam Deck not working

### ISSUE THREAD

**Issue by Whheat** [kuroppoi/brainwine#22]
I’m aware that steam deck isn’t officially supported but if there’s something I’m missing I’d like to know. If not, can steam deck/Linux support be put on the roadmap?

**Comment by Whheat** [comment]
I’ve made it as far as getting the jar to run and the server working, but the deepworld game itself doesn’t appear to be connecting to it. I suspect it’s due to the Windows registry files not doing anything in Linux but I’m no professional.

**Comment by kuroppoi** [comment]
That’s a tricky one, I’m surprised that the game even runs at all! Unfortunately, I do not own a Steam Deck and can not fiddle around with it myself. Deepworld (V3) uses Unity’s [PlayerPrefs](https://docs.unity3d.com/ScriptReference/PlayerPrefs.html) for fetching the gateway/API hosts and on Windows this happens to be the registry. You could try to see if you can find out where they are stored on the Steam Deck and see if it’s possible to modify them.

By the way, I assume you’re running the server on a regular PC?

**Comment by Whheat** [comment]
I’ve only tried running the server and the game on the deck at the same time, before I set up a server elsewhere. However I will check for the PlayerPrefs.

**Comment by kuroppoi** [comment]
If it’s Linux-based it might be worth checking out `~/.config/unity3d/Bytebin LLC/Deepworld`, if that means anything to you.

**Comment by Whheat** [comment]
No Bytebin in unity3d folder, but I guess I should be more specific with my issues. The game and server run and the server starts, but the account creation won’t work and that leads me to believe the client and server aren’t connected, however I’m no expert on servers and especially new to semi-reboots of gone too soon mmos.

**Comment by Whheat** [comment]
I may need to run the server from a regular pc but the only real options I have are my old MacBook and my raspberry pi.

**Comment by kuroppoi** [comment]
You can run the server on whatever you want, but it needs those PlayerPrefs keys to connect to it

**Comment by xnoe** [comment]
I'm not sure the exact path of compatdata on the Steam Deck but at least for Steam on my Arch Linux machines modifying the `~/.local/share/Steam/steamapps/compatdata/340810/pfx/user.reg` file to have the required registry values allows me to connect to the server just fine.

**Comment by kuroppoi** [comment]
And no such path exists on your Steam Deck?

**Comment by Whheat** [comment]
I’ll check soon, I’ve had a busy week this weekend should be a good time to check.

**Comment by Whheat** [comment]
> I'm not sure the exact path of compatdata on the Steam Deck but at least for Steam on my Arch Linux machines modifying the `~/.local/share/Steam/steamapps/compatdata/340810/pfx/user.reg` file to have the required registry values allows me to connect to the server just fine.

I found it! But I have no idea what to do now.

**Comment by kuroppoi** [comment]
Not sure how it works on Linux, but try something along the lines of creating a key called `gateway` in that location and setting its value to `local` (if you’re running the server on the same machine you’re playing on)

**Comment by harl** [comment]
Hah! Thanks for this.  It actually works so far.  I'm on Linux Mint here, so maybe this little feedback can help someone.

The file (user.reg) that's to be edited is actually in the Steam library directory, but not in the game's directory.
e.g. `/media/harl/Expansion/SteamLibrary/steamapps/compatdata/340810/pfx/user.reg`
whereas Expansion is the label of the volume where my main Steam library is saved.

Within the file, search for the key listed as **"[Software\\Bytebin LLC\\Deepworld]**" (or just for "Bytebin"),
then simply add a new value at the end of that paragraph:  **"gateway"="local"**

I started the server on Brainwine and then just started Deepworld via Steam (after editing user.reg).
It said "@ local" under the buttons, and I was able to register and login right away.

(Note that I didn't need to enable any specific compatibility settings in Steam either.)

**Comment by Ferynix** [comment]
@Whheat @harl @xnoe 
For future users- The game and server must be in the same wine instance if you want the simplest setup to do this entirely locally.. Install brainwine inside your wine instance, and configure the startup command / executable to be the brainwine runner. From there start the game inside of it.

This will allow you to play a fully boxed-in server on-client. Mind you- The V3 client has to be modified to work on the steamdeck with controller, and I havent fully polished it

We could probably package brainwine inside of a client at some point but thats a whole other set of shenanigans
