### ISSUE TITLE
Unable to connect to local server with patched Ipa File on IOS

### ISSUE THREAD

**Issue by Lanchochik228** [kuroppoi/brainwine#24]
When I patch the Ipa File I paste my IPV4 Address Everything worked out! I downloaded this ipa on my IPhone, turn on the server and set the IPV4 of My Computer to the server itself I go to Deepworld And enter my Account Entered all the data And when I press the "Go" button, the gear freezes and writes an error (Fail time Request) I tried to create a New character! Tried restarting the computer! Still the same error. What to do?

**Comment by kuroppoi** [comment]
Check the following:
- Make sure that `game_server_ip` in your `api.json` is correct. Should be an IPv4 literal; 4 digits separated by dots.
- Make sure that you entered the correct address when patching your IPA. Example: if the host IP is 12.345.67.89, you should enter `http://12.345.67.89:5001`.
- Make sure that you messed with no other settings on the server, such as ports.
- Make sure that the server actually started successfully with no errors in the console.
- Make sure that your phone and computer are on the same network.

**Comment by kuroppoi** [comment]
Inactive
