### ISSUE TITLE
Error Lost connection upon connection

### ISSUE THREAD

**Issue by oggiv** [kuroppoi/brainwine#25]
I'm trying to set up a Brainwine instance on a vps, but am having an issue where the connection is lost right as I enter the game.

The news text shows up as it should and my user gets added as I've been able to admin them from the server console without problem. Still, I can't enter the game. I click Play, a loading cog flashes for a short moment, "Loading Praparing scene..." shows for a bit, another loading cog flashes but this time with a gray background, then I'm shown a box over the main menu saying "Error Lost connection" which I can "Okay" away.

In logs/latest.log I find one line of interest:
`[netty-1-2/WARN] [/[myiphere]:57466]: readAddress(..) failed: Connection reset by peer`
I would have expected this to be shown once for each of my connection attempts but there is only one such line, so I'm not sure of it's relevance to this very issue.

I'm hosting Brainwine on a vps. Ports 5001-5003 should be open according to nmap on my local machine. I am able to download /clients from the gateway using wget as well.

My game runs fine when connecting to a local instance of Brainwine instead.

Is this a bug or have I overlooked something in my setup?

**Comment by kuroppoi** [comment]
You may have forgotten to configure the`api.json` file that brainwine generates on first-time startup. You need to make sure that `game_server_ip` points to your VPS.

**Comment by oggiv** [comment]
This was indeed the problem. Issue resolved.
Thank you

**Comment by oggiv** [comment]
Issue resolved.
