### ISSUE TITLE
Customization in client 1.12.1

### ISSUE THREAD

**Issue by Lanchochik228** [kuroppoi/brainwine#28]
I can not understand. how to customize a character in 1.12.1 Tried through a wardrobe And a mirror in any way Can you say Is there such a function at all?

**Comment by kuroppoi** [comment]
I think you indeed had to use a wardrobe or mirror, but brainwine doesn’t support that at the moment.

**Comment by Lanchochik228** [comment]
Wardrobe not working and mirror. But Ok thanks.
