### ISSUE TITLE
Can't Log In/Create Account

### ISSUE THREAD

**Issue by Trees4454** [kuroppoi/brainwine#37]
I haven't been able to find any explanation on how to create account. Every time I try to, I get a message saying "Couldn't connect to the search service. Please try again in a bit." Is there any way to circumvent this? I haven't even seen anyone else talking about this.

**Comment by kuroppoi** [comment]
It should let you create an account after starting the server and launching the game through brainwine.

**Comment by Trees4454** [comment]
Right, and when I try to, that's where I get the message. Since as far as I can tell a way wasn't implemented to play without an account(?) I'm pretty much stuck at the sign-up page because I can't get it to work.

**Comment by MailboxYig** [comment]
Gotta launch it thru the server called brainwine start the server then
launch deepworld

**Comment by Trees4454** [comment]
Yes... that's what I'm doing. I run the server and launch the game from there, and when I'm at the home page I click to sign up. I type in whatever info and enter, and then receive the "Couldn't connect to the search service. Please try again in a bit" message. I'm currently stuck here.

**Comment by MailboxYig** [comment]
Does the game say local underneath the signing. If not there's something
wrong with the server

**Comment by kuroppoi** [comment]
Like MailboxYig said, it's possible that your game host settings are wrong or the server isn't starting correctly.
Check the server logs and make sure there aren't any errors.
