### ISSUE TITLE
How do I fix "The request timed out" when logging into my account on iOS

### ISSUE THREAD

**Issue by CassOffGas** [kuroppoi/brainwine#39]
It also says that even if I try clicking "New Player", I used Sideloadly to get the game onto my iPhone.

**Comment by kuroppoi** [comment]
Removing the `http://` part when patching the .ipa file worked for the previous person who had this issue.

**Comment by CassOffGas** [comment]
I did that, now it says "unsupported URL"

**Comment by CassOffGas** [comment]
I tried leaving http:// in and now it says "Could not connect to the server" even after starting the server on brainwine.

**Comment by kuroppoi** [comment]
Then make sure you’re patching the correct server IP. If you’re hosting on your Mac then it should be the private IP address of that.

If you’re connecting via private IP you must also ensure that your phone and your Mac are both connected to the same network.

Lastly, make sure that the value of `game_server_ip` in the `api.json` file is also set to the host’s private IP (requires server restart after changing it)

**Comment by CassOffGas** [comment]
I'm not sure what I did wrong, but for some reason it is still saying "Could not connect to the server."

**Comment by kuroppoi** [comment]
Which gateway host did you patch your game with and what does your `api.json` look like?

**Comment by CassOffGas** [comment]
Gateway Host: http://192.168.88.15
api.json (screenshot)
<img width="643" alt="Screenshot 2024-04-07 at 7 37 27 AM" src="https://github.com/kuroppoi/brainwine/assets/166205802/1dfc8ff1-a40a-4b3c-8341-20b72f3fdd55">

**Comment by kuroppoi** [comment]
Patch the game with `http://192.168.88.15:5001` as the gateway host.

**Comment by CassOffGas** [comment]
It is now working! Thanks again!

**Comment by kuroppoi** [comment]
Good to hear! I'm sorry that it's such a pain to set up 🤣

**Comment by CassOffGas** [comment]
It's all right! Just glad it's working now.
