### ISSUE TITLE
Hey i just want to kinda dabble in making android work again

### ISSUE THREAD

**Issue by MailboxYig** [kuroppoi/brainwine#40]
I tried downloading an app file of the webs and it's made for an older version and won't launch correctly (black screen) I was wondering what kind of apps or dev tools are needed for tinkering

**Comment by kuroppoi** [comment]
If the app is outdated then I don't know if there's anything you can do about it.
APK files are really just zip archives so it should be easy to take a look inside of them, but I don't know what you'll be looking for.
The Android version is built with Unity (which uses C#) so the assembly of the game itself can be decompiled and modified very easily with tools such as [dnSpy](https://github.com/dnSpy/dnSpy).
