### ISSUE TITLE
Multiplayer not working for some reason

### ISSUE THREAD

**Issue by CassOffGas** [kuroppoi/brainwine#41]
I tried installing Deepworld on my friend's iPhone 15 and when using Sideloadly it fails and says what is attached in the screenshot
<img width="415" alt="Screenshot 2024-04-08 at 9 03 43 PM" src="https://github.com/kuroppoi/brainwine/assets/166205802/51fe694c-a1b2-4884-86f4-05c684a75164">
We enabled Developer Mode, it does not come up on VPN & Device Management to trust it, Deepworld is on the Home Screen but only in the cloud and can't be opened. Says what is in the second screenshot.
![IMG_B9FCFE23BA34-1](https://github.com/kuroppoi/brainwine/assets/166205802/cdb066e1-5ca2-4fb0-9777-d044172f8c0f)

**Comment by MailboxYig** [comment]
Maybe the repackager got checked and couldn't be verified

**Comment by kuroppoi** [comment]
I'm afraid I can't provide much support when it comes to sideloading apps, sinceI'm not too familiar with it myself.
I'd suggest trying out solutions on the internet.

**Comment by CassOffGas** [comment]
> Maybe the repackager got checked and couldn't be verified

How do I fix this? Is there a way to?

**Comment by CassOffGas** [comment]
I'll just check out solutions online. Thanks though!
