### ISSUE TITLE
It wants me to relog but I can't log out because I haven't done /register yet

### ISSUE THREAD

**Issue by CassOffGas** [kuroppoi/brainwine#42]
When I try clicking on Play it says "The provided session token is invalid or has expired. Please try relogging."
But I can't log out to relog because it says "Before you can log out, you must register your current account. Log in and type /register in the console to register."

**Comment by kuroppoi** [comment]
Yes, this cycle of doom unfortunately happens way more often than I'd like.
If you're on iOS, you might be screwed. Deleting the app and all of its data might solve the issue.
If the issue occurs on MacOS, you'll have to download the [latest dev build](https://github.com/kuroppoi/brainwine/actions/runs/8622151289/artifacts/1399256609) and use the experimental account lock remover which can be found under the 'Help' menu tab.

For MacOS you can also execute the following command in terminal:
```
defaults delete com.bytebin.deepworld playerLocked
```

**Comment by CassOffGas** [comment]
Thank you for the help. It worked! Closing this as completed now.
