### ISSUE TITLE
For windows, Do I download JDK or JRE?

### ISSUE THREAD

**Issue by CassOffGas** [kuroppoi/brainwine#43]
Also, what do I open brainwine with? because no apps come up on my windows PC to open brainwine with, even after downloading JDK 22 and JRE 8. the only thing that comes up is the java setup wizard, which i know isn't what i should be using.

**Comment by CassOffGas** [comment]
Also, Deepworld shows "local" underneath "new player". The issue right now is just that I can't open brainwine because Java won't show up as an app. For some reason only the setup is coming up. Not sure why.

**Comment by CassOffGas** [comment]
Since Deepworld said "@local" underneath New player and looked like it was working, I tried just clicking on log in to log in to my account, but all it says is "Couldn't connect to the search service, Please try again in a bit."

**Comment by CassOffGas** [comment]
I tried executing the host.reg, which is probably why Deepworld says "local" underneath "New player"

**Comment by kuroppoi** [comment]
You only need a JRE to run Java programs, and the JDK includes one so it doesn't really matter which one you choose.
If you've installed Java on Windows but can't run any .jar files then it might be worth giving [jarfix](https://johann.loefflmann.net/en/software/jarfix/index.html) a shot.
Just make sure that you've actually installed Java (and not just downloaded it.)

**Comment by CassOffGas** [comment]
I used jarfix and everything is working now! Thanks for your help!
