### ISSUE TITLE
Local Server Play

### ISSUE THREAD

**Issue by AtomicHusky** [kuroppoi/brainwine#8]
Recently, I've been trying to connect to a friends server on a local shared network. 
If I were hosting a server, the host.reg file I would execute would tell deepworld to connect to: 
"gateway"="local"
"api"="local"

Say I wanted to connect to a friend on the same network. What pattern or way should I put in the IP and PORT. 
I've tried:
"gateway"="127.0.0.1:5001" **<--- [For both I've tried the game_server_ip (127.0.0.1), game_server_port (5002), gateway_port, (5001) and portal_port (5003).]**
"api"="127.0.0.1:5001"
None of these seem to be working, please help me find the correct way and order to put in the IP:PORT in order to connect to my friend.

**Comment by kuroppoi** [comment]
If you’re on the same network then you should use the host machine’s (the machine running the server) private ip address. Aside from that, the IP:PORT format is correct.

**Comment by kuroppoi** [comment]
Gonna assume the issue is no longer relevant
